IS_OS_8_OR_HIGHER = UIDevice.currentDevice.systemVersion.floatValue >= 8.0
# this constants should be listed here to be accessible in constantize

UIControlContentHorizontalAlignmentCenter
UIControlContentHorizontalAlignmentLeft
UIControlContentHorizontalAlignmentRight
UIControlContentHorizontalAlignmentFill

UIControlContentVerticalAlignmentCenter
UIControlContentVerticalAlignmentTop
UIControlContentVerticalAlignmentBottom
UIControlContentVerticalAlignmentFill

if defined?(ALAssetsLibrary)
  ALAssetsLibrary
end

if defined?(ALAuthorizationStatusNotDetermined)
  ALAuthorizationStatusNotDetermined
end

if defined?(ALAssetsGroupAll)
  ALAssetsGroupAll
end
