source 'http://rubygems.org'

gem 'cocoapods', '~> 0.19.1'
gem 'motion-cocoapods', '~> 1.3.2'
gem 'motion-support', '~> 0.2.4'
gem 'sugarcube', '~> 0.20.23'
gem 'bubble-wrap', '~> 1.3.0'
gem 'nano-store', '~> 0.6.3'

gem 'motion-prime', '~> 0.3.0'