source 'http://rubygems.org'

gem 'motion-cocoapods', '~> 1.4.1'
gem 'motion-prime', '1.0.6'

# add reside menu for sidebar support
# gem 'prime_reside_menu', '~> 0.1.4'

# or add sliding menu for sidebar support
# gem 'prime_sliding_menu', '~> 0.1.5'
