source 'http://rubygems.org'

gem 'motion-cocoapods', '~> 1.4.0'
gem 'motion-support', '~> 0.2.4'

gem 'motion-prime', '0.8.1'

# add reside menu for sidebar support
gem 'prime_reside_menu', '~> 0.1.4'

# or add sliding menu for sidebar support
# gem 'prime_sliding_menu', '~> 0.1.5'
